namespace GGService2.DAL.Classes.Enums
{
  public enum ENotificationTypes
  {
    NOTIFICATION_TYPE_CLAN,
    NOTIFICATION_TYPE_TRANSACTION,
    NOTIFICATION_TYPE_CLAN_ACCEPTED,
    NOTIFICATION_TYPE_CLAN_CANCELED,
    NOTIFICATION_TYPE_BATTLE_JOINED,
    NOTIFICATION_TYPE_REWARD_OF_THE_DAY,
    NOTIFICATION_TYPE_ELO_CHANGED,
  }
}
